apiVersion: v1
kind: Service
metadata:
  name: bms-service
  namespace: sairam-namespace
  labels:
    app: bms
spec:
  type: LoadBalancer   
  ports:
    - port: 80         
      targetPort: 3000 
  selector:
    app: bms
